### ISSUE TITLE
Capitalize XLib in CMakeLists.txt

### ISSUE THREAD

**Issue by jeaton32** [hornet-gt/hornet#18]
The Linux filesystems are case sensitive, so the references to XLib have to be changed from 'xlib' to 'XLib' or the cmake fails to find the associated files.

**Comment by kaatish** [comment]
The XLib submodule is cloned to externals/xlib, so I do not think there should be a problem.

1. Can you paste the output of CMake?
2. Can you display the contents of externals/xlib?
3. How have you cloned Hornet? Have you used recursive flag?
