### ISSUE TITLE
KTruss test file

### ISSUE THREAD

**Issue by maawad** [hornet-gt/hornet#37]
Hello, 
I'm trying to reproduce some of your results (GTC18 talk) and I was wondering where I can find the K-Truss algorithm test files. I looked into `hornet/hornetsnest/test/` but I can't see the test file there. 
Thanks,

**Comment by ogreen** [comment]
Take a look at the code: 
https://github.com/ogreen/cuStingerAlg/tree/ktruss/tests
or
https://github.com/foxjas/cuStingerAlg/blob/ktruss/test/KTrusstest.cu
One of these should have an older yet working version of the code.
