### ISSUE TITLE
Hornet Build Errors

### ISSUE THREAD

**Issue by SaraRehmat** [hornet-gt/hornet#39]
I am planning to use Hornet for my academic research. While building Hornet I get the following errors. Can anyone guide me here why these errors are showing up and how to fix them. Thanks

/hornet/hornet/include/Core/DataLayout/DataLayout.i.cuh(144): error: expected an expression
          detected during:
            instantiation of "hornets_nest::vid_t *hornets_nest::gpu::Vertex<hornets_nest::TypeList<VertexTypes...>, hornets_nest::TypeList<EdgeTypes...>, FORCE_SOA>::neighbor_ptr() const [with VertexTypes=<>, EdgeTypes=<>, FORCE_SOA=false]" 
/hornet/include/Core/GPUHornet/impl/HornetKernels.cuh(50): here
            instantiation of "void hornets_nest::gpu::printKernel(HornetDevice) [with HornetDevice=hornets_nest::gpu::HornetDevice<hornets_nest::TypeList<>, hornets_nest::TypeList<>, false>]" 
/hornet/include/Core/GPUHornet/impl/Hornet2.i.cuh(47): here
            instantiation of "void hornets_nest::gpu::Hornet<hornets_nest::TypeList<VertexTypes...>, hornets_nest::TypeList<EdgeTypes...>, FORCE_SOA>::print() [with VertexTypes=<>, EdgeTypes=<>, FORCE_SOA=false]" 
/hornet/test/HornetTest.cu(71): here

/hornet/include/Core/DataLayout/DataLayout.i.cuh(144): error: expected an expression
          detected during:
            instantiation of "hornets_nest::gpu::Vertex<hornets_nest::TypeList<VertexTypes...>, hornets_nest::TypeList<EdgeTypes...>, FORCE_SOA>::EdgeT hornets_nest::gpu::Vertex<hornets_nest::TypeList<VertexTypes...>, hornets_nest::TypeList<EdgeTypes...>, FORCE_SOA>::edge(hornets_nest::degree_t) const [with VertexTypes=<>, EdgeTypes=<>, FORCE_SOA=false]" 
/hornet/hornet/include/Core/GPUHornet/Batch/Kernels/BatchCommonKernels.cuh(117): here
            instantiation of "void hornets_nest::gpu::bulkMarkDuplicate<BLOCK_SIZE,HornetDevice>(HornetDevice, const int *, const int *, const hornets_nest::vid_t *, const hornets_nest::vid_t *, int, __nv_bool *) [with BLOCK_SIZE=128, HornetDevice=hornets_nest::gpu::HornetDevice<hornets_nest::TypeList<>, hornets_nest::TypeList<>, false>]" 
/hornet/hornet/include/Core/GPUHornet/Batch/BatchCommon.i.cuh(166): here
            instantiation of "void hornets_nest::gpu::Hornet<hornets_nest::TypeList<VertexTypes...>, hornets_nest::TypeList<EdgeTypes...>, FORCE_SOA>::remove_cross_duplicates(hornets_nest::gpu::BatchUpdate &, hornets_nest::vid_t *, hornets_nest::vid_t *, size_t *) [with VertexTypes=<>, EdgeTypes=<>, FORCE_SOA=false]" 
/hornet/include/Core/GPUHornet/Batch/BatchCommon.i.cuh(202): here
            instantiation of "int hornets_nest::gpu::Hornet<hornets_nest::TypeList<VertexTypes...>, hornets_nest::TypeList<EdgeTypes...>, FORCE_SOA>::batch_preprocessing(hornets_nest::gpu::BatchUpdate &, hornets_nest::gpu::BatchProperty, __nv_bool) [with VertexTypes=<>, EdgeTypes=<>, FORCE_SOA=false]" 
/hornet/include/Core/GPUHornet/Batch/BatchInsert.i.cuh(48): here
            instantiation of "void hornets_nest::gpu::Hornet<hornets_nest::TypeList<VertexTypes...>, hornets_nest::TypeList<EdgeTypes...>, FORCE_SOA>::insertEdgeBatch(hornets_nest::gpu::BatchUpdate &, hornets_nest::gpu::BatchProperty) [with VertexTypes=<>, EdgeTypes=<>, FORCE_SOA=false]" 
/hornet/test/HornetInsertTest.cu(54): here

/hornet/include/Core/DataLayout/DataLayout.i.cuh(144): error: expected an expression
          detected during:
            instantiation of "hornets_nest::vid_t *hornets_nest::gpu::Vertex<hornets_nest::TypeList<VertexTypes...>, hornets_nest::TypeList<EdgeTypes...>, FORCE_SOA>::neighbor_ptr() const [with VertexTypes=<>, EdgeTypes=<>, FORCE_SOA=false]" 
hornet/include/Core/GPUHornet/impl/HornetKernels.cuh(50): here
            instantiation of "void hornets_nest::gpu::printKernel(HornetDevice) [with HornetDevice=hornets_nest::gpu::HornetDevice<hornets_nest::TypeList<>, hornets_nest::TypeList<>, false>]" 
/hornet/include/Core/GPUHornet/impl/Hornet2.i.cuh(47): here
            instantiation of "void hornets_nest::gpu::Hornet<hornets_nest::TypeList<VertexTypes...>, hornets_nest::TypeList<EdgeTypes...>, FORCE_SOA>::print() [with VertexTypes=<>, EdgeTypes=<>, FORCE_SOA=false]" 
/hornet/hornet/test/HornetDeleteTest.cu(26): here

**Comment by SaraRehmat** [comment]
I am using CUDA-10.1.

**Comment by kaatish** [comment]
This has been fixed in the latest push. Could you please try again?
