### ISSUE TITLE
How to output the result of SSSP?

### ISSUE THREAD

**Issue by bookug** [hornet-gt/hornet#45]
i.e., the distance array.
I know that the logic is in hornetsnest/src/Static/ShortestPath/SSSP.cu,  SSSP::run().
But what is the weight_t type?

**Comment by bookug** [comment]
there is a d_distance array. How can I copy it to Host and output?   I use cudaMemcpy but it fails to produce the correct results.

**Comment by kaatish** [comment]
> i.e., the distance array.
> I know that the logic is in hornetsnest/src/Static/ShortestPath/SSSP.cu, SSSP::run().
> But what is the weight_t type?

`weight_t` is set [here](https://github.com/hornet-gt/hornet/blob/master/hornetsnest/include/Static/ShortestPath/SSSP.cuh#L47) and is equal to `int`.

Can you talk about what kind of failure are you experiencing? Are the values different than what you expect?

**Comment by bookug** [comment]
yes, the values are all 2147483647

**Comment by bookug** [comment]
I do not know why ...     can not I use cudaMemcpy?   (RMM is used in Hornet)

**Comment by bookug** [comment]
Is there anyone who can answer my question?
Is this repository really alive?

**Comment by bookug** [comment]
@kaatish @ogreen @foxjas @devavret

**Comment by kaatish** [comment]
@bookug I am looking into it.

**Comment by bookug** [comment]
Are you ok? How about the question?  @kaatish @ogreen @foxjas @devavret

**Comment by kaatish** [comment]
I changed the validate function in src/Static/ShortestPath/SSSP.cu to this :

```
bool SSSP::validate() {
    std::cout<<"Distances\n";
    thrust::device_vector<weight_t> dist(hornet.nV());
    thrust::copy(thrust::device, d_distances, d_distances + hornet.nV(), dist.begin());
    thrust::copy(dist.begin(), dist.end(), std::ostream_iterator<weight_t>(std::cout, " "));
    return true;
}
```

Here is the result I am getting with karate.mtx :

```
Graph File: karate             Size: 0 MB        format: (Market)

@File    V: 34            E: 156           Structure: Undirected   avg. deg: 4.5
   100%
COO to CSR...	Complete!

Levels : 5
         SSSP  1.3 ms
Distances
0 42 33 56 94 0 9 30 86 100 14 23 9 40 85 117 52 18 86 39 152 34 99 105 108 114 126 75 79 147 62 67 85 72 
Correct <>
```

Can you tell me which graph file are you using and what is the root that you are specifying?

**Comment by kaatish** [comment]
@bookug Any updates on your end?

**Comment by bookug** [comment]
I see... I will try this and see what happens.

**Comment by bookug** [comment]
It works, thanks:)
